[project]
name = "cloudidesandbox"
version = "0.1.0"
description = ""
authors = [
    {name = "Ruslan",email = "pprrg18@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.139.0,<0.140.0)",
    "uvicorn (>=0.49.0,<0.50.0)",
    "docker (>=7.1.0,<8.0.0)",
    "websockets (>=16.1,<17.0)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "alembic (>=1.19.0,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "cloudidesandbox", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
